Music.Web/Areas/Admin/Controllers/AlbumsController.cs
using Music.Model.Dao;
using Music.Model.EF;
using System;
using System.Data.Entity;
using System.IO;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Music.Web.Areas.Admin.Controllers
{
    public class AlbumsController : BaseController
    {
        private RunNow db = new RunNow();

        public async Task<ActionResult> Index()
        {
            var albums = db.albums.Include(a => a.singer);
            return View(await albums.ToListAsync());
        }

        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            album album = await db.albums.FindAsync(id);
            if (album == null)
            {
                return HttpNotFound();
            }
            return View(album);
        }

        public ActionResult Create()
        {
            ViewBag.singer_id = new SelectList(db.singers, "singer_id", "singer_name");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "album_id,singer_id,album_name,album_createdate,album_image,album_view,album_viewed_day,album_viewed_week,album_viewed_month")] album album, HttpPostedFileBase Upload)
        {
            if (ModelState.IsValid)
            {
                var file = Request.Files[0];
                if (file != null && file.ContentLength > 0)
                {
                    string _FileName = Path.GetFileName(file.FileName);
                    string _Ext = Path.GetExtension(file.FileName);
                    string path = Path.Combine(Server.MapPath("~/source/images/"), _FileName);
                    album.album_image = "~/source/images/" + _FileName;
                    Upload.SaveAs(path);
                }
                album.album_view = 1;
                album.album_viewed_day = 1;
                album.album_viewed_week = 1;
                album.album_viewed_month = 1;
                db.albums.Add(album);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.singer_id = new SelectList(db.singers, "singer_id", "singer_name", album.singer_id);
            return View(album);
        }

        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            album album = await db.albums.FindAsync(id);
            if (album == null)
            {
                return HttpNotFound();
            }
            ViewBag.singer_id = new SelectList(db.singers, "singer_id", "singer_name", album.singer_id);
            return View(album);
        }

        // POST: Admin/Albums/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "album_id,singer_id,album_name,album_createdate,album_image")] album album, HttpPostedFileBase Upload)
        {
            if (ModelState.IsValid)
            {
                var path = "";
                var file = Request.Files[0];
                if (file != null && file.ContentLength > 0)
                {
                    string _FileName = Path.GetFileName(file.FileName);
                    string _Ext = Path.GetExtension(file.FileName);
                    path = Path.Combine(Server.MapPath("~/source/images/"), _FileName);
                    // Kiễm tra tồn tại file.
                    if (System.IO.File.Exists(path))
                    {
                        System.IO.File.Delete(path);
                    }
                    album.album_image = "~/source/images/" + _FileName;
                    album.album_createdate = DateTime.Now;
                    Upload.SaveAs(path);
                }
                db.Entry(album).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.singer_id = new SelectList(db.singers, "singer_id", "singer_name", album.singer_id);
            return View();
        }

        [HttpDelete]
        public ActionResult Delete(int? id)
        {
            try
            {
                new AlbumDAO().Delete(id);
            }
            catch (Exception)
            {
                ModelState.AddModelError("", "Xoa kho");
            }

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Music.Web/Controllers/AlbumController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Music.Model.EF;

namespace Music.Web.Controllers
{
    public class AlbumController : Controller
    {
        private RunNow db = new RunNow();

        // GET: Albums
        public async Task<ActionResult> Index()
        {
            var albums = db.albums.Include(a => a.singer);
            return View(await albums.ToListAsync());
        }

        // GET: Albums/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            album album = await db.albums.FindAsync(id);
            if (album == null)
            {
                return HttpNotFound();
            }
            return View(album);
        }

        // GET: Albums/Create
        public ActionResult Create()
        {
            ViewBag.singer_id = new SelectList(db.singers, "singer_id", "singer_name");
            return View();
        }

        // POST: Albums/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "album_id,singer_id,album_name,album_createdate,album_image,album_view,album_viewed_day,album_viewed_week,album_viewed_month")] album album)
        {
            if (ModelState.IsValid)
            {
                db.albums.Add(album);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.singer_id = new SelectList(db.singers, "singer_id", "singer_name", album.singer_id);
            return View(album);
        }

        // GET: Albums/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            album album = await db.albums.FindAsync(id);
            if (album == null)
            {
                return HttpNotFound();
            }
            ViewBag.singer_id = new SelectList(db.singers, "singer_id", "singer_name", album.singer_id);
            return View(album);
        }

        // POST: Albums/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "album_id,singer_id,album_name,album_createdate,album_image,album_view,album_viewed_day,album_viewed_week,album_viewed_month")] album album)
        {
            if (ModelState.IsValid)
            {
                db.Entry(album).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.singer_id = new SelectList(db.singers, "singer_id", "singer_name", album.singer_id);
            return View(album);
        }

        // GET: Albums/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            album album = await db.albums.FindAsync(id);
            if (album == null)
            {
                return HttpNotFound();
            }
            return View(album);
        }

        // POST: Albums/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            album album = await db.albums.FindAsync(id);
            db.albums.Remove(album);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Music.Web/Areas/Admin/Views/Albums/Create.cshtml
@model Music.Model.EF.album

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "Albums", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>album</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.singer_id, "singer_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("singer_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.singer_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.album_name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.album_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.album_name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.album_image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="Upload" />
                <br />
                @Html.ValidationMessageFor(model => model.album_image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Music.Web/Areas/Admin/Views/Albums/Details.cshtml
@model Music.Model.EF.album

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>album</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.singer.singer_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.singer.singer_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.album_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.album_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.album_createdate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.album_createdate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.album_image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.album_image)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.album_view)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.album_view)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.album_viewed_day)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.album_viewed_day)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.album_viewed_week)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.album_viewed_week)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.album_viewed_month)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.album_viewed_month)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.album_id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Music.Web/Areas/Admin/Views/Albums/Edit.cshtml
@model Music.Model.EF.album

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>album</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.album_id)

        <div class="form-group">
            @Html.LabelFor(model => model.singer_id, "singer_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("singer_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.singer_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.album_name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.album_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.album_name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.album_image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="Upload" />
                @Html.ValidationMessageFor(model => model.album_image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Music.Web/Areas/Admin/Views/Albums/Index.cshtml
@model IEnumerable<Music.Model.EF.album>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<a href="~/Admin/Albums/Create">

    <i class="fa fa-fw fa-plus">
    </i>Thêm Album
</a>
<table class="table" id="Select-b" style="table-layout:fixed;">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.singer.singer_name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.album_name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.album_createdate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.album_image)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.album_view)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.singer.singer_name)
            </td>
            <td id="appadd">
                @Html.DisplayFor(modelItem => item.album_name)
            </td>
            <td id="appadd">
                @Html.DisplayFor(modelItem => item.album_createdate)
            </td>
            <td>
                <img width="170" height="50" src="@Url.Content(item.album_image)" alt="@Url.Content(item.album_name)" />
            </td>
            <td id="appadd">
                @Html.DisplayFor(modelItem => item.album_view)
            </td>
            <td id="del">
                @Html.ActionLink(" ", "Edit", new { id = item.album_id }, new { @class = "fa fa-fw fa-edit" }) |
                @Html.ActionLink(" ", "Details", new { id = item.album_id }, new { @class = "fa fa-fw fa-info" }) |
                @Ajax.ActionLink(" ","Delete",new { id = item.album_id },new AjaxOptions {
               Confirm="Xóa "+ item.album_name +" ?",
               OnComplete="$('del').remove()",
               HttpMethod = "Delete"
           },new { @class="fa fa-fw fa-trash"})
            </td>
        </tr>
    }
</table>